linters:
  enable:
    - gocritic
    - gosec
    - misspell
    - revive
    - unconvert
    - goconst
    - nilerr
    - exhaustive
    - prealloc
    - whitespace
    - nolintlint

linters-settings:
  goconst:
    min-len: 3
    min-occurrences: 3
  revive:
    rules:
      - name: blank-imports
      - name: exported
        disabled: true
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
  exhaustive:
    default-signifies-exhaustive: true
  gosec:
    excludes:
      - G104 # unhandled errors — already covered by errcheck
