version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/agent.go
    binary: dbtune-agent
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    ignore:
      - goos: darwin
        goarch: amd64

dockers:
  - image_templates:
      - "public.ecr.aws/dbtune/dbtune/agent:{{ .Version }}"
      - "public.ecr.aws/dbtune/dbtune/agent:latest"
    dockerfile: Dockerfile
    extra_files:
      - go.mod
      - go.sum
      - cmd/
      - pkg/
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=dbtune-agent"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  use: github

  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "Merge pull request"

  groups:
    - title: "🚀 Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "🧰 Maintenance"
      regexp: "^.*chore[(\\w)]*:+.*$"
      order: 2
    - title: "📝 Documentation"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 3
    - title: Other
      order: 999

announce:
  slack:
    enabled: true
    message_template: "🚀 new DBTune Agent {{.Tag}} release. [Changelog]({{.Changelog}})"
    channel: "testingbot"
    username: "Platform release"
