# Example of PostgreSQL cluster
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3

  # Bootstrap configuration to create pg_stat_statements extension
  bootstrap:
    initdb:
      database: app
      owner: app
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

  postgresql:
    parameters:
      pg_stat_statements.track: all  # Weird, but otherwise pgss won't be included

  # Require 1Gi of space
  storage:
    size: 1Gi
