version: "3"

tasks:
  start-dev-postgres:
    desc: Start development postgresql instance
    cmds:
      - docker rm -f dev-postgres
      - mkdir -p ./volumes/dev-postgres
      - docker run --name dev-postgres
        --memory="500m"
        -e POSTGRES_PASSWORD=password
        -e POSTGRES_USER=dbtune
        -p 1994:5432
        -v ./volumes/dev-postgres:/var/lib/postgresql/data
        -v ./templates/init.sql:/docker-entrypoint-initdb.d/init.sql
        -d postgres
        -c shared_preload_libraries=pg_stat_statements
        -c pg_stat_statements.track=all
    silent: false

  start-testing-db:
    desc: Start a new testing database with agent
    cmds:
      - ./scripts/local-testing.sh
    silent: false

  test:
    desc: Run tests
    cmds:
      - go test ./... -v

  build:
    desc: Build
    cmds:
      - go build -x -o dbtune-agent ./cmd/agent.go


