//go:build integration

package queries

import (
	"context"
	"fmt"
	"io"
	"regexp"
	"sort"
	"strings"
	"testing"

	tcexec "github.com/testcontainers/testcontainers-go/exec"

	"github.com/jackc/pgx/v5/pgxpool"
)

// ---------------------------------------------------------------------------
// Golden schema fixtures — exercises all DDL features we support.
// ---------------------------------------------------------------------------

var goldenSchemaFixtures = []string{
	// ================================================================
	// Types
	// ================================================================
	`CREATE TYPE mood AS ENUM ('happy', 'sad', 'neutral')`,

	`CREATE DOMAIN email_addr AS text CHECK (VALUE ~ '@')`,
	`CREATE DOMAIN positive_int AS integer NOT NULL CHECK (VALUE > 0)`,

	// Cross-schema enum: type lives in a non-public schema but is used by
	// a public table — must appear in the DDL output.
	`CREATE SCHEMA IF NOT EXISTS custom_types`,
	`CREATE TYPE custom_types.status AS ENUM ('on', 'off', 'standby')`,

	// ================================================================
	// Sequences
	// ================================================================
	`CREATE SEQUENCE global_id_seq AS bigint START WITH 1000 INCREMENT BY 1`,
	`CREATE SEQUENCE cyclic_seq AS integer START WITH 1 INCREMENT BY 1 CYCLE`,

	// ================================================================
	// Functions
	// ================================================================
	`CREATE FUNCTION add_numbers(a integer, b integer) RETURNS integer
	 AS $$ BEGIN RETURN a + b; END; $$ LANGUAGE plpgsql`,
	`CREATE FUNCTION update_timestamp() RETURNS trigger
	 AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END; $$ LANGUAGE plpgsql`,

	// ================================================================
	// Tables — exercises all column types, modifiers, and edge cases
	// ================================================================

	// Comprehensive column types + collation + domain/enum references.
	`CREATE TABLE users (
		id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
		username text NOT NULL,
		email email_addr,
		display_name text COLLATE "C",
		mood mood DEFAULT 'neutral',
		score positive_int DEFAULT 1,
		bio text,
		created_at timestamptz DEFAULT now(),
		updated_at timestamptz
	)`,

	// Serial column (generates implicit sequence + ownership link).
	`CREATE TABLE categories (
		id serial PRIMARY KEY,
		name text NOT NULL UNIQUE,
		description text DEFAULT ''
	)`,

	// Various constraint types + CHECK + UNIQUE composite + FK.
	`CREATE TABLE products (
		id bigint DEFAULT nextval('global_id_seq') PRIMARY KEY,
		name text NOT NULL,
		category_id integer REFERENCES categories(id),
		price numeric(10,2) NOT NULL CHECK (price >= 0),
		weight real,
		tags text[],
		metadata jsonb DEFAULT '{}',
		UNIQUE (name, category_id)
	)`,

	// Generated stored column + GENERATED BY DEFAULT AS IDENTITY.
	`CREATE TABLE orders (
		id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		product_id bigint REFERENCES products(id),
		user_id integer REFERENCES users(id),
		quantity integer NOT NULL CHECK (quantity > 0),
		unit_price numeric(10,2) NOT NULL,
		total numeric(10,2) GENERATED ALWAYS AS (quantity * unit_price) STORED,
		ordered_at timestamptz DEFAULT now()
	)`,

	// Storage parameters (fillfactor, autovacuum).
	`CREATE TABLE audit_log (
		id bigint GENERATED ALWAYS AS IDENTITY,
		action text NOT NULL,
		payload jsonb,
		created_at timestamptz DEFAULT now()
	) WITH (fillfactor=90, autovacuum_vacuum_scale_factor=0.01)`,

	// Comprehensive column type coverage — every common PG type in one table.
	`CREATE TABLE all_types (
		col_integer integer,
		col_bigint bigint,
		col_smallint smallint,
		col_text text,
		col_boolean boolean,
		col_real real,
		col_double double precision,
		col_varchar varchar(100),
		col_char char(10),
		col_numeric numeric(10,2),
		col_timestamp timestamp,
		col_timestamptz timestamptz,
		col_date date,
		col_time time,
		col_interval interval,
		col_uuid uuid,
		col_json json,
		col_jsonb jsonb,
		col_bytea bytea,
		col_int_array integer[],
		col_text_array text[],
		col_inet inet,
		col_cidr cidr,
		col_macaddr macaddr,
		col_tsvector tsvector,
		col_xml xml
	)`,

	// Reserved-word table and column names (tests identifier quoting).
	`CREATE TABLE "user" (
		"order" integer,
		"select" text,
		"from" boolean DEFAULT true
	)`,

	// Mixed-case column names (must be quoted to survive round-trip).
	`CREATE TABLE quoted_cols (
		"userId" integer,
		"createdAt" timestamptz DEFAULT now(),
		normal_col text
	)`,

	// Many columns (tests large table handling).
	`CREATE TABLE many_columns (
		col_00 integer, col_01 integer, col_02 integer, col_03 integer, col_04 integer,
		col_05 integer, col_06 integer, col_07 integer, col_08 integer, col_09 integer,
		col_10 integer, col_11 integer, col_12 integer, col_13 integer, col_14 integer,
		col_15 integer, col_16 integer, col_17 integer, col_18 integer, col_19 integer,
		col_20 integer, col_21 integer, col_22 integer, col_23 integer, col_24 integer
	)`,

	// Various DEFAULT expressions.
	`CREATE TABLE default_expressions (
		int_default integer DEFAULT 42,
		str_default text DEFAULT 'hello',
		bool_default boolean DEFAULT true,
		now_default timestamptz DEFAULT now(),
		expr_default integer DEFAULT 1 + 1,
		uuid_default uuid DEFAULT gen_random_uuid()
	)`,

	// Cross-schema type reference.
	`CREATE TABLE device_status (
		id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
		name text NOT NULL,
		status custom_types.status DEFAULT 'off'
	)`,

	// Table that will have a dropped column (should NOT appear in DDL).
	`CREATE TABLE dropped_col_test (keep_me integer, drop_me text)`,
	`ALTER TABLE dropped_col_test DROP COLUMN drop_me`,

	// ================================================================
	// Partitioning
	// ================================================================
	`CREATE TABLE events (
		id bigint GENERATED ALWAYS AS IDENTITY,
		event_type text NOT NULL,
		payload jsonb,
		created_at date NOT NULL
	) PARTITION BY RANGE (created_at)`,
	`CREATE TABLE events_2023 PARTITION OF events
	 FOR VALUES FROM ('2023-01-01') TO ('2024-01-01')`,
	`CREATE TABLE events_2024 PARTITION OF events
	 FOR VALUES FROM ('2024-01-01') TO ('2025-01-01')`,

	`CREATE TABLE notifications (
		id bigint GENERATED ALWAYS AS IDENTITY,
		channel text NOT NULL,
		message text
	) PARTITION BY LIST (channel)`,
	`CREATE TABLE notifications_email PARTITION OF notifications
	 FOR VALUES IN ('email')`,
	`CREATE TABLE notifications_sms PARTITION OF notifications
	 FOR VALUES IN ('sms')`,

	// ================================================================
	// Inheritance
	// ================================================================
	`CREATE TABLE base_entity (
		id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
		name text NOT NULL,
		created_at timestamptz DEFAULT now()
	)`,
	`CREATE TABLE extended_entity (extra_data jsonb) INHERITS (base_entity)`,

	// ================================================================
	// Foreign keys — self-referencing, circular
	// ================================================================
	`CREATE TABLE tree_nodes (
		id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
		parent_id integer REFERENCES tree_nodes(id),
		label text NOT NULL
	)`,

	`CREATE TABLE team (
		id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
		name text NOT NULL,
		lead_id integer
	)`,
	`CREATE TABLE employee (
		id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
		name text NOT NULL,
		team_id integer REFERENCES team(id)
	)`,
	`ALTER TABLE team ADD CONSTRAINT team_lead_fk
	 FOREIGN KEY (lead_id) REFERENCES employee(id)`,

	// ================================================================
	// Indexes — btree, unique, multi-column, partial, expression, GIN, BRIN, hash, INCLUDE
	// ================================================================
	`CREATE INDEX idx_users_username ON users (username)`,
	`CREATE UNIQUE INDEX idx_users_email ON users (email)`,
	`CREATE INDEX idx_products_tags ON products USING gin (tags)`,
	`CREATE INDEX idx_products_metadata ON products USING gin (metadata)`,
	`CREATE INDEX idx_products_name_lower ON products (lower(name))`,
	`CREATE INDEX idx_orders_recent ON orders (ordered_at DESC)`,
	`CREATE INDEX idx_audit_created ON audit_log USING brin (created_at)`,
	`CREATE INDEX idx_orders_active ON orders (user_id) WHERE quantity > 1`,
	`CREATE INDEX idx_products_name_hash ON products USING hash (name)`,
	`CREATE INDEX idx_all_types_text ON all_types (col_text) INCLUDE (col_integer)`,

	// ================================================================
	// Exclusion constraint (requires btree_gist extension)
	// ================================================================
	`CREATE EXTENSION IF NOT EXISTS btree_gist`,
	`CREATE TABLE room_bookings (
		room integer,
		during tstzrange,
		EXCLUDE USING gist (room WITH =, during WITH &&)
	)`,

	// ================================================================
	// Views + materialized views
	// ================================================================
	`CREATE VIEW active_users AS
	 SELECT id, username, email FROM users WHERE mood <> 'sad'`,
	`CREATE VIEW order_summary AS
	 SELECT u.username, COUNT(*) AS order_count, SUM(o.total) AS total_spent
	 FROM orders o JOIN users u ON u.id = o.user_id
	 GROUP BY u.username`,

	`CREATE MATERIALIZED VIEW product_stats AS
	 SELECT p.name, COUNT(o.id) AS order_count, SUM(o.total) AS revenue
	 FROM products p LEFT JOIN orders o ON o.product_id = p.id
	 GROUP BY p.name`,

	// ================================================================
	// Triggers
	// ================================================================
	`CREATE TRIGGER trg_users_updated
	 BEFORE UPDATE ON users
	 FOR EACH ROW EXECUTE FUNCTION update_timestamp()`,

	// ================================================================
	// Row-level security
	// ================================================================
	`ALTER TABLE orders ENABLE ROW LEVEL SECURITY`,
	`CREATE POLICY orders_owner_read ON orders
	 FOR SELECT USING (user_id = current_setting('app.user_id')::integer)`,
	`CREATE POLICY orders_owner_insert ON orders
	 FOR INSERT WITH CHECK (user_id = current_setting('app.user_id')::integer)`,

	// ================================================================
	// UNLOGGED table
	// ================================================================
	`CREATE UNLOGGED TABLE session_cache (
		session_id text PRIMARY KEY,
		data jsonb,
		expires_at timestamptz
	)`,

	// ================================================================
	// Column SET STORAGE override
	// ================================================================
	`CREATE TABLE storage_override (
		id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
		small_data text,
		big_blob bytea
	)`,
	`ALTER TABLE storage_override ALTER COLUMN big_blob SET STORAGE EXTERNAL`,

	// ================================================================
	// Column SET STATISTICS override
	// ================================================================
	`CREATE TABLE stats_override (
		id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
		high_cardinality text,
		low_cardinality text
	)`,
	`ALTER TABLE stats_override ALTER COLUMN high_cardinality SET STATISTICS 1000`,
	`ALTER TABLE stats_override ALTER COLUMN low_cardinality SET STATISTICS 10`,

	// ================================================================
	// View with security_barrier option
	// ================================================================
	`CREATE VIEW secure_users WITH (security_barrier=true) AS
	 SELECT id, username FROM users`,

	// ================================================================
	// RLS policy with non-PUBLIC roles
	// ================================================================
	`CREATE ROLE test_reader LOGIN`,
	`CREATE ROLE test_writer LOGIN`,
	`CREATE TABLE role_scoped (
		id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
		owner_name text NOT NULL,
		data text
	)`,
	`ALTER TABLE role_scoped ENABLE ROW LEVEL SECURITY`,
	`CREATE POLICY reader_policy ON role_scoped
	 FOR SELECT TO test_reader
	 USING (true)`,
	`CREATE POLICY writer_policy ON role_scoped
	 FOR INSERT TO test_writer
	 WITH CHECK (owner_name = current_user)`,

	// ================================================================
	// Bigserial column
	// ================================================================
	`CREATE TABLE big_ids (
		id bigserial PRIMARY KEY,
		label text
	)`,

	// ================================================================
	// Hash partitioning
	// ================================================================
	`CREATE TABLE hash_partitioned (
		id integer NOT NULL,
		data text
	) PARTITION BY HASH (id)`,
	`CREATE TABLE hash_partitioned_0 PARTITION OF hash_partitioned
	 FOR VALUES WITH (MODULUS 2, REMAINDER 0)`,
	`CREATE TABLE hash_partitioned_1 PARTITION OF hash_partitioned
	 FOR VALUES WITH (MODULUS 2, REMAINDER 1)`,

	// ================================================================
	// DEFERRABLE constraints
	// ================================================================
	`CREATE TABLE deferred_parent (
		id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY
	)`,
	`CREATE TABLE deferred_child (
		id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
		parent_id integer,
		CONSTRAINT deferred_fk FOREIGN KEY (parent_id)
			REFERENCES deferred_parent(id) DEFERRABLE INITIALLY DEFERRED
	)`,

	// ================================================================
	// Procedures (distinct from functions, PG 11+)
	// ================================================================
	`CREATE PROCEDURE do_nothing()
	 LANGUAGE plpgsql
	 AS $$ BEGIN NULL; END; $$`,

	// ================================================================
	// Multiple and named CHECK constraints
	// ================================================================
	`CREATE TABLE multi_check (
		x integer,
		y integer,
		z integer,
		CONSTRAINT x_positive CHECK (x > 0),
		CONSTRAINT y_positive CHECK (y > 0),
		CONSTRAINT sum_limit CHECK (x + y < 1000)
	)`,

	// ================================================================
	// Composite primary key
	// ================================================================
	`CREATE TABLE composite_pk (
		tenant_id integer NOT NULL,
		item_id integer NOT NULL,
		value text,
		PRIMARY KEY (tenant_id, item_id)
	)`,

	// ================================================================
	// FK with ON DELETE/ON UPDATE actions
	// ================================================================
	`CREATE TABLE fk_actions_parent (
		id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
		name text NOT NULL
	)`,
	`CREATE TABLE fk_actions_child (
		id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
		parent_id integer,
		nullable_ref integer,
		CONSTRAINT fk_cascade FOREIGN KEY (parent_id)
			REFERENCES fk_actions_parent(id) ON DELETE CASCADE ON UPDATE CASCADE,
		CONSTRAINT fk_setnull FOREIGN KEY (nullable_ref)
			REFERENCES fk_actions_parent(id) ON DELETE SET NULL ON UPDATE SET NULL
	)`,

	// ================================================================
	// FK with MATCH FULL
	// ================================================================
	`CREATE TABLE match_full_parent (
		a integer, b integer,
		PRIMARY KEY (a, b)
	)`,
	`CREATE TABLE match_full_child (
		id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
		ref_a integer,
		ref_b integer,
		CONSTRAINT fk_match_full FOREIGN KEY (ref_a, ref_b)
			REFERENCES match_full_parent(a, b) MATCH FULL
	)`,

	// ================================================================
	// Multiple triggers on same table + conditional trigger (WHEN) + statement-level
	// ================================================================
	`CREATE FUNCTION log_insert() RETURNS trigger
	 AS $$ BEGIN RETURN NEW; END; $$ LANGUAGE plpgsql`,
	`CREATE FUNCTION log_statement() RETURNS trigger
	 AS $$ BEGIN RETURN NULL; END; $$ LANGUAGE plpgsql`,
	`CREATE TABLE multi_trigger (
		id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
		status text DEFAULT 'new',
		updated_at timestamptz
	)`,
	`CREATE TRIGGER trg_multi_before_insert
	 BEFORE INSERT ON multi_trigger
	 FOR EACH ROW EXECUTE FUNCTION log_insert()`,
	`CREATE TRIGGER trg_multi_after_update
	 AFTER UPDATE ON multi_trigger
	 FOR EACH ROW WHEN (OLD.status IS DISTINCT FROM NEW.status)
	 EXECUTE FUNCTION update_timestamp()`,
	`CREATE TRIGGER trg_multi_statement
	 AFTER INSERT ON multi_trigger
	 FOR EACH STATEMENT EXECUTE FUNCTION log_statement()`,

	// ================================================================
	// INSTEAD OF trigger on a view
	// ================================================================
	`CREATE FUNCTION view_insert_handler() RETURNS trigger
	 AS $$ BEGIN INSERT INTO multi_trigger (status) VALUES (NEW.status); RETURN NEW; END; $$ LANGUAGE plpgsql`,
	`CREATE VIEW multi_trigger_view AS SELECT id, status FROM multi_trigger`,
	`CREATE TRIGGER trg_instead_of_insert
	 INSTEAD OF INSERT ON multi_trigger_view
	 FOR EACH ROW EXECUTE FUNCTION view_insert_handler()`,

	// ================================================================
	// RESTRICTIVE RLS policy
	// ================================================================
	`ALTER TABLE role_scoped FORCE ROW LEVEL SECURITY`,
	`CREATE POLICY restrictive_deny ON role_scoped AS RESTRICTIVE
	 FOR ALL USING (owner_name <> 'blocked')`,

	// ================================================================
	// Index on materialized view
	// ================================================================
	`CREATE UNIQUE INDEX idx_product_stats_name ON product_stats (name)`,

	// ================================================================
	// Composite type
	// ================================================================
	`CREATE TYPE address AS (
		street text,
		city text,
		zip text,
		country text
	)`,
	`CREATE TABLE contacts (
		id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
		name text NOT NULL,
		home_address address,
		work_address address
	)`,

	// ================================================================
	// Partial unique index
	// ================================================================
	`CREATE UNIQUE INDEX idx_multi_trigger_active
	 ON multi_trigger (status) WHERE status <> 'deleted'`,

	// ================================================================
	// Multi-column index with mixed sort orders
	// ================================================================
	`CREATE INDEX idx_orders_mixed_sort
	 ON orders (user_id ASC, ordered_at DESC NULLS FIRST)`,

	// ================================================================
	// Scope exclusions — non-public schema table (must NOT appear in output)
	// ================================================================
	`CREATE SCHEMA IF NOT EXISTS private_schema`,
	`CREATE TABLE private_schema.hidden_table (val integer)`,
}

// goldenSchemaFixturesPG15 contains fixtures that require PG 15+.
var goldenSchemaFixturesPG15 = []string{
	// NULLS NOT DISTINCT on unique index (PG 15+)
	`CREATE TABLE nulls_not_distinct (
		id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
		code text
	)`,
	`CREATE UNIQUE INDEX idx_nulls_not_distinct
	 ON nulls_not_distinct (code) NULLS NOT DISTINCT`,
}

// ---------------------------------------------------------------------------
// Catalog snapshot — queries the same catalogs on two databases and compares.
// ---------------------------------------------------------------------------

// catalogSnapshot holds the key catalog state of a database schema.
type catalogSnapshot struct {
	Tables      []string // sorted "tablename|relkind|reloptions"
	Columns     []string // sorted "tablename|attnum|colname|typename|notnull|default|identity|generated"
	Constraints []string // sorted "tablename|conname|contype|condef"
	Indexes     []string // sorted "indexname|indexdef"
	Sequences   []string // sorted "seqname|datatype|start|increment|cycle"
	Types       []string // sorted "schema.typename|typtype"
	Functions   []string // sorted "funcname|funcdef"
	Triggers    []string // sorted "tablename|trigname|trigdef"
	Views       []string // sorted "viewname|viewdef"
	Policies    []string // sorted "tablename|polname|polcmd|permissive|qual|withcheck"
	ForeignKeys []string // sorted "tablename|conname|condef"
	Partitions  []string // sorted "child|parent|bound"
	Inherits    []string // sorted "child|parent"
}

func takeCatalogSnapshot(pool *pgxpool.Pool, ctx context.Context) (*catalogSnapshot, error) {
	snap := &catalogSnapshot{}
	var err error

	// Tables
	snap.Tables, err = queryStringSlice(pool, ctx, `
		SELECT c.relname || '|' || c.relkind::text || '|' || COALESCE(array_to_string(c.reloptions, ','), '')
		FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
		WHERE n.nspname = 'public' AND c.relkind IN ('r','p')
		ORDER BY c.relname`)
	if err != nil {
		return nil, fmt.Errorf("tables: %w", err)
	}

	// Columns
	snap.Columns, err = queryStringSlice(pool, ctx, `
		SELECT c.relname || '|' || a.attnum || '|' || a.attname || '|' ||
		       format_type(a.atttypid, a.atttypmod) || '|' || a.attnotnull || '|' ||
		       COALESCE(pg_get_expr(d.adbin, d.adrelid), '') || '|' ||
		       COALESCE(a.attidentity::text, '') || '|' ||
		       COALESCE(a.attgenerated::text, '')
		FROM pg_attribute a
		JOIN pg_class c ON c.oid = a.attrelid
		JOIN pg_namespace n ON n.oid = c.relnamespace
		LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
		WHERE n.nspname = 'public' AND c.relkind IN ('r','p')
		  AND a.attnum > 0 AND NOT a.attisdropped
		ORDER BY c.relname, a.attnum`)
	if err != nil {
		return nil, fmt.Errorf("columns: %w", err)
	}

	// Constraints (non-FK)
	snap.Constraints, err = queryStringSlice(pool, ctx, `
		SELECT c.relname || '|' || con.conname || '|' || con.contype::text || '|' ||
		       pg_get_constraintdef(con.oid)
		FROM pg_constraint con
		JOIN pg_class c ON c.oid = con.conrelid
		JOIN pg_namespace n ON n.oid = c.relnamespace
		WHERE n.nspname = 'public' AND con.contype IN ('p','u','c','x')
		ORDER BY c.relname, con.conname`)
	if err != nil {
		return nil, fmt.Errorf("constraints: %w", err)
	}

	// Foreign keys
	snap.ForeignKeys, err = queryStringSlice(pool, ctx, `
		SELECT c.relname || '|' || con.conname || '|' || pg_get_constraintdef(con.oid)
		FROM pg_constraint con
		JOIN pg_class c ON c.oid = con.conrelid
		JOIN pg_namespace n ON n.oid = c.relnamespace
		WHERE n.nspname = 'public' AND con.contype = 'f'
		ORDER BY c.relname, con.conname`)
	if err != nil {
		return nil, fmt.Errorf("foreign keys: %w", err)
	}

	// Indexes (exclude constraint-backing indexes)
	snap.Indexes, err = queryStringSlice(pool, ctx, `
		SELECT indexname || '|' || indexdef
		FROM pg_indexes
		WHERE schemaname = 'public'
		  AND indexname NOT IN (
		      SELECT c.relname
		      FROM pg_constraint con
		      JOIN pg_class c ON c.oid = con.conindid
		      JOIN pg_namespace n ON n.oid = c.relnamespace
		      WHERE n.nspname = 'public'
		  )
		ORDER BY indexname`)
	if err != nil {
		return nil, fmt.Errorf("indexes: %w", err)
	}

	// Sequences (exclude identity-backing sequences)
	snap.Sequences, err = queryStringSlice(pool, ctx, `
		SELECT c.relname || '|' || format_type(s.seqtypid, NULL) || '|' ||
		       s.seqstart || '|' || s.seqincrement || '|' || s.seqcycle
		FROM pg_class c
		JOIN pg_namespace n ON n.oid = c.relnamespace
		JOIN pg_sequence s ON s.seqrelid = c.oid
		WHERE n.nspname = 'public' AND c.relkind = 'S'
		  AND NOT EXISTS (
		      SELECT 1 FROM pg_depend d
		      WHERE d.objid = c.oid
		        AND d.deptype = 'i'
		        AND d.refclassid = 'pg_class'::regclass
		  )
		ORDER BY c.relname`)
	if err != nil {
		return nil, fmt.Errorf("sequences: %w", err)
	}

	// Types (enums + domains)
	snap.Types, err = queryStringSlice(pool, ctx, `
		SELECT quote_ident(tn.nspname) || '.' || quote_ident(t.typname) || '|' || t.typtype::text
		FROM pg_type t
		JOIN pg_namespace tn ON tn.oid = t.typnamespace
		WHERE t.typtype IN ('e','d')
		  AND t.oid IN (
		      SELECT DISTINCT a.atttypid FROM pg_attribute a
		      JOIN pg_class c ON c.oid = a.attrelid
		      JOIN pg_namespace n ON n.oid = c.relnamespace
		      WHERE n.nspname = 'public' AND c.relkind IN ('r','p')
		        AND a.attnum > 0 AND NOT a.attisdropped
		  )
		ORDER BY tn.nspname, t.typname`)
	if err != nil {
		return nil, fmt.Errorf("types: %w", err)
	}

	// Functions (exclude extension-owned)
	snap.Functions, err = queryStringSlice(pool, ctx, `
		SELECT p.proname || '|' || pg_get_functiondef(p.oid)
		FROM pg_proc p
		JOIN pg_namespace n ON n.oid = p.pronamespace
		WHERE n.nspname = 'public' AND p.prokind IN ('f','p')
		  AND NOT EXISTS (
		      SELECT 1 FROM pg_depend d
		      WHERE d.objid = p.oid AND d.deptype = 'e'
		  )
		ORDER BY p.proname, p.oid`)
	if err != nil {
		return nil, fmt.Errorf("functions: %w", err)
	}

	// Triggers
	snap.Triggers, err = queryStringSlice(pool, ctx, `
		SELECT c.relname || '|' || t.tgname || '|' || pg_get_triggerdef(t.oid)
		FROM pg_trigger t
		JOIN pg_class c ON c.oid = t.tgrelid
		JOIN pg_namespace n ON n.oid = c.relnamespace
		WHERE n.nspname = 'public' AND NOT t.tgisinternal
		ORDER BY c.relname, t.tgname`)
	if err != nil {
		return nil, fmt.Errorf("triggers: %w", err)
	}

	// Views + materialized views
	snap.Views, err = queryStringSlice(pool, ctx, `
		SELECT c.relname || '|' || c.relkind::text || '|' || pg_get_viewdef(c.oid)
		FROM pg_class c
		JOIN pg_namespace n ON n.oid = c.relnamespace
		WHERE n.nspname = 'public' AND c.relkind IN ('v','m')
		  AND NOT EXISTS (
		      SELECT 1 FROM pg_depend d
		      WHERE d.objid = c.oid AND d.deptype = 'e'
		  )
		ORDER BY c.relname`)
	if err != nil {
		return nil, fmt.Errorf("views: %w", err)
	}

	// RLS policies
	snap.Policies, err = queryStringSlice(pool, ctx, `
		SELECT c.relname || '|' || pol.polname || '|' || pol.polcmd::text || '|' || pol.polpermissive || '|' ||
		       COALESCE(pg_get_expr(pol.polqual, pol.polrelid), '') || '|' ||
		       COALESCE(pg_get_expr(pol.polwithcheck, pol.polrelid), '')
		FROM pg_policy pol
		JOIN pg_class c ON c.oid = pol.polrelid
		JOIN pg_namespace n ON n.oid = c.relnamespace
		WHERE n.nspname = 'public'
		ORDER BY c.relname, pol.polname`)
	if err != nil {
		return nil, fmt.Errorf("policies: %w", err)
	}

	// Partition relationships
	snap.Partitions, err = queryStringSlice(pool, ctx, `
		SELECT c.relname || '|' || pc.relname || '|' || pg_get_expr(c.relpartbound, c.oid)
		FROM pg_inherits i
		JOIN pg_class c ON c.oid = i.inhrelid
		JOIN pg_class pc ON pc.oid = i.inhparent
		JOIN pg_namespace n ON n.oid = c.relnamespace
		WHERE n.nspname = 'public' AND pc.relkind = 'p'
		ORDER BY pc.relname, c.relname`)
	if err != nil {
		return nil, fmt.Errorf("partitions: %w", err)
	}

	// Inheritance (non-partition)
	snap.Inherits, err = queryStringSlice(pool, ctx, `
		SELECT c.relname || '|' || pc.relname
		FROM pg_inherits i
		JOIN pg_class c ON c.oid = i.inhrelid
		JOIN pg_class pc ON pc.oid = i.inhparent
		JOIN pg_namespace n ON n.oid = c.relnamespace
		WHERE n.nspname = 'public' AND pc.relkind = 'r'
		ORDER BY c.relname, pc.relname`)
	if err != nil {
		return nil, fmt.Errorf("inheritance: %w", err)
	}

	return snap, nil
}

// queryStringSlice runs a query and returns all rows as a sorted string slice.
func queryStringSlice(pool *pgxpool.Pool, ctx context.Context, query string) ([]string, error) {
	rows, err := pool.Query(ctx, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var result []string
	for rows.Next() {
		var s string
		if err := rows.Scan(&s); err != nil {
			return nil, err
		}
		result = append(result, s)
	}
	sort.Strings(result)
	return result, rows.Err()
}

// compareCatalogSnapshots compares two snapshots and returns a human-readable diff.
// Returns empty string if identical.
func compareCatalogSnapshots(source, replayed *catalogSnapshot) string {
	var diffs []string

	check := func(label string, src, rep []string) {
		d := diffStringSlices(label, src, rep)
		if d != "" {
			diffs = append(diffs, d)
		}
	}

	check("tables", source.Tables, replayed.Tables)
	check("columns", source.Columns, replayed.Columns)
	check("constraints", source.Constraints, replayed.Constraints)
	check("foreign_keys", source.ForeignKeys, replayed.ForeignKeys)
	check("indexes", source.Indexes, replayed.Indexes)
	check("sequences", source.Sequences, replayed.Sequences)
	check("types", source.Types, replayed.Types)
	check("functions", source.Functions, replayed.Functions)
	check("triggers", source.Triggers, replayed.Triggers)
	check("views", source.Views, replayed.Views)
	check("policies", source.Policies, replayed.Policies)
	check("partitions", source.Partitions, replayed.Partitions)
	check("inheritance", source.Inherits, replayed.Inherits)

	return strings.Join(diffs, "\n")
}

// diffStringSlices returns a human-readable diff of two sorted string slices.
func diffStringSlices(label string, a, b []string) string {
	setA := make(map[string]bool, len(a))
	setB := make(map[string]bool, len(b))
	for _, s := range a {
		setA[s] = true
	}
	for _, s := range b {
		setB[s] = true
	}

	var missing, extra []string
	for _, s := range a {
		if !setB[s] {
			missing = append(missing, s)
		}
	}
	for _, s := range b {
		if !setA[s] {
			extra = append(extra, s)
		}
	}

	if len(missing) == 0 && len(extra) == 0 {
		return ""
	}

	var b2 strings.Builder
	fmt.Fprintf(&b2, "[%s] mismatch:\n", label)
	for _, s := range missing {
		fmt.Fprintf(&b2, "  - (in source, not replayed): %s\n", s)
	}
	for _, s := range extra {
		fmt.Fprintf(&b2, "  + (in replayed, not source):  %s\n", s)
	}
	return b2.String()
}

// ---------------------------------------------------------------------------
// pg_dump comparison helpers
// ---------------------------------------------------------------------------

// pgDumpSchemaOnly runs pg_dump --schema-only inside the container and returns
// the normalized output.
func pgDumpSchemaOnly(t *testing.T, inst pgInstance, dbName string) string {
	t.Helper()
	ctx := context.Background()

	exitCode, reader, err := inst.container.Exec(ctx,
		[]string{
			"pg_dump",
			"--schema-only",
			"--no-owner",
			"--no-privileges",
			"--no-comments",
			"--no-security-labels",
			"--no-tablespaces",
			"--no-publications",
			"--no-subscriptions",
			"-d", dbName,
			"-U", "test",
		},
		tcexec.Multiplexed(),
	)
	if err != nil {
		t.Fatalf("pg_dump exec failed: %v", err)
	}

	output, err := io.ReadAll(reader)
	if err != nil {
		t.Fatalf("pg_dump read output failed: %v", err)
	}

	if exitCode != 0 {
		t.Fatalf("pg_dump exited %d: %s", exitCode, string(output))
	}

	return normalizePgDump(string(output))
}

// Patterns to strip from pg_dump output for comparison.
var pgDumpStripPatterns = []*regexp.Regexp{
	regexp.MustCompile(`(?m)^--.*$`),                                                       // all comments
	regexp.MustCompile(`(?m)^SET .*;\s*$`),                                                 // SET statements
	regexp.MustCompile(`(?m)^SELECT pg_catalog\..*;\s*$`),                                  // SELECT pg_catalog calls
	regexp.MustCompile(`(?m)^ALTER .* OWNER TO .*;\s*$`),                                   // ownership
	regexp.MustCompile(`(?m)^GRANT .*;\s*$`),                                               // grants
	regexp.MustCompile(`(?m)^REVOKE .*;\s*$`),                                              // revokes
	regexp.MustCompile(`(?m)^\\\.\s*$`),                                                    // COPY terminators
	regexp.MustCompile(`(?m)^\\restrict\s+.*$`),                                            // \restrict lines
	regexp.MustCompile(`(?m)^\\unrestrict\s+.*$`),                                          // \unrestrict lines
	regexp.MustCompile(`(?m)^CREATE EXTENSION .*;\s*$`),                                    // extension creation
	regexp.MustCompile(`(?m)^CREATE SCHEMA .*;\s*$`),                                       // non-public schema creation
	regexp.MustCompile(`(?ms)^CREATE TABLE private_schema\..*?;\s*$`),                      // non-public schema tables (multiline)
	regexp.MustCompile(`(?m)^ALTER SEQUENCE .* OWNED BY .*;\s*$`),                          // sequence ownership
	regexp.MustCompile(`(?m)^ALTER TABLE .* ALTER COLUMN .* SET DEFAULT nextval\(.*;\s*$`), // serial default setup
}

// normalizePgDump strips metadata, comments, SET statements, and collapses
// blank lines so two pg_dump outputs can be compared semantically.
func normalizePgDump(dump string) string {
	// Normalize line endings
	dump = strings.ReplaceAll(dump, "\r\n", "\n")

	// Strip patterns
	for _, re := range pgDumpStripPatterns {
		dump = re.ReplaceAllString(dump, "")
	}

	// Collapse multiple blank lines into one
	dump = regexp.MustCompile(`\n{3,}`).ReplaceAllString(dump, "\n\n")

	return strings.TrimSpace(dump)
}

// ---------------------------------------------------------------------------
// Round-trip test
// ---------------------------------------------------------------------------

func TestDDL_RoundTrip(t *testing.T) {
	for _, inst := range pgInstances {
		t.Run(fmt.Sprintf("pg%d", inst.version), func(t *testing.T) {
			ctx := context.Background()
			sourceDB := fmt.Sprintf("ddl_source_%d", inst.version)
			replayDB := fmt.Sprintf("ddl_replay_%d", inst.version)

			// 1. Create a dedicated source database with only our golden schema.
			_, _ = inst.admin.Exec(ctx, "DROP DATABASE IF EXISTS "+sourceDB)
			_, err := inst.admin.Exec(ctx, "CREATE DATABASE "+sourceDB)
			if err != nil {
				t.Fatalf("CREATE DATABASE %s failed: %v", sourceDB, err)
			}
			t.Cleanup(func() {
				_, _ = inst.admin.Exec(ctx, "DROP DATABASE IF EXISTS "+sourceDB)
			})

			sourceConnStr := replaceDBInConnStr(inst.admin, sourceDB)
			sourceAdmin, err := pgxpool.New(ctx, sourceConnStr)
			if err != nil {
				t.Fatalf("failed to connect to source DB: %v", err)
			}
			defer sourceAdmin.Close()

			// Set up golden schema fixtures in the source DB.
			for _, sql := range goldenSchemaFixtures {
				if _, err := sourceAdmin.Exec(ctx, sql); err != nil {
					t.Fatalf("fixture setup failed: %s\nerror: %v", sql, err)
				}
			}
			// Version-conditional fixtures.
			if inst.version >= 15 {
				for _, sql := range goldenSchemaFixturesPG15 {
					if _, err := sourceAdmin.Exec(ctx, sql); err != nil {
						t.Fatalf("PG15+ fixture setup failed: %s\nerror: %v", sql, err)
					}
				}
			}

			// Create pg_monitor role in source DB so CollectDDL works.
			for _, sql := range []string{
				`DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'monitor') THEN CREATE ROLE monitor LOGIN PASSWORD 'monitor'; END IF; END $$`,
				`GRANT pg_monitor TO monitor`,
			} {
				if _, err := sourceAdmin.Exec(ctx, sql); err != nil {
					t.Fatalf("monitor setup in source DB: %v", err)
				}
			}

			// Connect to source DB as pg_monitor.
			monitorConnStr := replaceDBInConnStr(inst.admin, sourceDB)
			monitorConnStr = strings.Replace(monitorConnStr, "user=test", "user=monitor", 1)
			monitorConnStr = strings.Replace(monitorConnStr, "password=test", "password=monitor", 1)
			sourceMonitor, err := pgxpool.New(ctx, monitorConnStr)
			if err != nil {
				t.Fatalf("failed to connect to source DB as monitor: %v", err)
			}
			defer sourceMonitor.Close()

			// 2. Collect DDL with our tool (as pg_monitor).
			ourDDL, err := CollectDDL(sourceMonitor, ctx)
			if err != nil {
				t.Fatalf("CollectDDL failed: %v", err)
			}
			if ourDDL == "" {
				t.Fatal("CollectDDL returned empty string")
			}

			// 3. Take catalog snapshot of source DB.
			sourceSnap, err := takeCatalogSnapshot(sourceAdmin, ctx)
			if err != nil {
				t.Fatalf("source catalog snapshot failed: %v", err)
			}

			// 4. Create fresh database and replay our DDL.
			_, _ = inst.admin.Exec(ctx, "DROP DATABASE IF EXISTS "+replayDB)
			_, err = inst.admin.Exec(ctx, "CREATE DATABASE "+replayDB)
			if err != nil {
				t.Fatalf("CREATE DATABASE %s failed: %v", replayDB, err)
			}
			t.Cleanup(func() {
				_, _ = inst.admin.Exec(ctx, "DROP DATABASE IF EXISTS "+replayDB)
			})

			replayConnStr := replaceDBInConnStr(inst.admin, replayDB)
			replayPool, err := pgxpool.New(ctx, replayConnStr)
			if err != nil {
				t.Fatalf("failed to connect to replay DB: %v", err)
			}
			defer replayPool.Close()

			// Replay our DDL.
			if _, err := replayPool.Exec(ctx, ourDDL); err != nil {
				t.Fatalf("replay of our DDL failed:\nerror: %v\nDDL:\n%s", err, ourDDL)
			}

			// 5. Catalog comparison: source vs replayed.
			replaySnap, err := takeCatalogSnapshot(replayPool, ctx)
			if err != nil {
				t.Fatalf("replay catalog snapshot failed: %v", err)
			}

			if diff := compareCatalogSnapshots(sourceSnap, replaySnap); diff != "" {
				t.Errorf("catalog mismatch between source and replayed DB:\n%s", diff)
			}

			// 6. pg_dump comparison: source vs replayed.
			sourceDump := pgDumpSchemaOnly(t, inst, sourceDB)
			replayDump := pgDumpSchemaOnly(t, inst, replayDB)

			if sourceDump != replayDump {
				t.Errorf("pg_dump output differs between source and replayed DB:\n%s",
					unifiedTextDiff(sourceDump, replayDump))
			}
		})
	}
}

// replaceDBInConnStr gets the connection config from an existing pool and
// replaces the database name.
func replaceDBInConnStr(pool *pgxpool.Pool, dbName string) string {
	cfg := pool.Config().ConnConfig.Copy()
	cfg.Database = dbName
	return fmt.Sprintf("host=%s port=%d user=%s password=%s dbname=%s sslmode=disable",
		cfg.Host, cfg.Port, cfg.User, cfg.Password, dbName)
}

// unifiedTextDiff produces a simple line-by-line diff between two strings.
func unifiedTextDiff(a, b string) string {
	linesA := strings.Split(a, "\n")
	linesB := strings.Split(b, "\n")

	var diff strings.Builder
	maxLen := len(linesA)
	if len(linesB) > maxLen {
		maxLen = len(linesB)
	}

	diffCount := 0
	for i := 0; i < maxLen; i++ {
		la, lb := "", ""
		if i < len(linesA) {
			la = linesA[i]
		}
		if i < len(linesB) {
			lb = linesB[i]
		}
		if la != lb {
			diffCount++
			if diffCount <= 50 { // cap output
				fmt.Fprintf(&diff, "line %d:\n  source:   %s\n  replayed: %s\n", i+1, la, lb)
			}
		}
	}
	if diffCount > 50 {
		fmt.Fprintf(&diff, "... and %d more differences\n", diffCount-50)
	}
	if diffCount == 0 && len(linesA) != len(linesB) {
		fmt.Fprintf(&diff, "line count differs: source=%d replayed=%d\n", len(linesA), len(linesB))
	}
	return diff.String()
}
